title: 銀河英語國際演講會
tagline: Galaxy Toastmaster Club
author:
  name: 'Leo Chen'
  twitter:

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Activities', url: 'activities.html'}
# - {name: 'Upcoming', url: 'upcoming.html'}

social:
- {icon: 'github', link: 'https://www.github.com/dapast1289'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:dpast1289l@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
